<?php

namespace App\Mail;

use App\Ticket;
use Illuminate\Bus\Queueable;
use Illuminate\Contracts\Queue\ShouldQueue;
use Illuminate\Mail\Mailable;
use Illuminate\Queue\SerializesModels;

class ReportTicket extends Mailable implements shouldQueue
{
    use Queueable, SerializesModels;

    public $ticket;

    /**
     * Create a new message instance.
     *
     * @return void
     */

    public function __construct(Ticket $ticket)
    {
        $this->ticket = $ticket;
    }

    /**
     * Build the message.
     *
     * @return $this
     */
    public function build()
    {
        return $this->markdown('emails.ticket.report');
    }

    public function from($address, $name = null)
    {
        return parent::from($address, $name); // TODO: Change the autogenerated stub
    }

    public function to($address, $name = null)
    {
        return parent::to($address, $name); // TODO: Change the autogenerated stub
    }


}
